
import { useIsMobile } from "@/hooks/use-mobile";
import { PurchaseOrderData } from "@/lib/po-service";
import { Download, Printer, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "sonner";

interface PurchaseOrderPreviewProps {
  poData: PurchaseOrderData | null;
}

const PurchaseOrderPreview = ({ poData }: PurchaseOrderPreviewProps) => {
  const isMobile = useIsMobile();
  
  if (!poData) {
    return (
      <div className="glass-panel p-6 text-center">
        <p className="text-muted-foreground">
          Use the form to create a purchase order
        </p>
      </div>
    );
  }
  
  const handlePrint = () => {
    window.print();
  };
  
  const handleDownload = () => {
    // In a real app, this would generate a PDF
    toast.success("Purchase order download started");
  };
  
  const handleShare = () => {
    toast.success("Sharing options opened");
  };
  
  const formatDate = (dateString: string) => {
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString('en-IN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    } catch (e) {
      return dateString;
    }
  };
  
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
    }).format(amount);
  };
  
  return (
    <div className="glass-panel p-6 animate-fade-in print:shadow-none print:border-none">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
        <h2 className="text-xl font-semibold">Purchase Order</h2>
        <div className="flex mt-4 md:mt-0 space-x-2">
          <Button size="sm" variant="outline" onClick={handlePrint} className="print:hidden">
            <Printer className="h-4 w-4 mr-2" />
            {!isMobile && "Print"}
          </Button>
          <Button size="sm" variant="outline" onClick={handleDownload} className="print:hidden">
            <Download className="h-4 w-4 mr-2" />
            {!isMobile && "Download"}
          </Button>
          <Button size="sm" variant="outline" onClick={handleShare} className="print:hidden">
            <Share2 className="h-4 w-4 mr-2" />
            {!isMobile && "Share"}
          </Button>
        </div>
      </div>
      
      <div className="mb-6 grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <h3 className="text-sm font-medium text-muted-foreground mb-1">Supplier</h3>
          <p className="font-medium">{poData.supplier_name}</p>
        </div>
        <div>
          <h3 className="text-sm font-medium text-muted-foreground mb-1">Delivery Date</h3>
          <p className="font-medium">{formatDate(poData.delivery_date)}</p>
        </div>
        <div>
          <h3 className="text-sm font-medium text-muted-foreground mb-1">Shipping Address</h3>
          <p className="font-medium">{poData.shipping_address}</p>
        </div>
        <div>
          <h3 className="text-sm font-medium text-muted-foreground mb-1">Payment Terms</h3>
          <p className="font-medium">{poData.payment_terms}</p>
        </div>
      </div>
      
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[50%]">Item Description</TableHead>
              <TableHead className="text-right">Qty</TableHead>
              <TableHead className="text-right">Unit Price</TableHead>
              <TableHead className="text-right">Amount</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {poData.items.map((item, index) => (
              <TableRow key={index}>
                <TableCell className="font-medium">{item.description}</TableCell>
                <TableCell className="text-right">{item.quantity}</TableCell>
                <TableCell className="text-right">{formatCurrency(item.unit_price)}</TableCell>
                <TableCell className="text-right">{formatCurrency(item.amount)}</TableCell>
              </TableRow>
            ))}
            <TableRow>
              <TableCell colSpan={3} className="text-right font-semibold">Total:</TableCell>
              <TableCell className="text-right font-bold">{formatCurrency(poData.total_amount)}</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
      
      <div className="mt-6 pt-6 border-t">
        <p className="text-sm text-muted-foreground">
          This purchase order was generated by AI based on your description.
        </p>
      </div>
    </div>
  );
};

export default PurchaseOrderPreview;
