
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { toast } from 'sonner';

/**
 * Utility function to handle printing the current page
 */
export const printInvoice = (): void => {
  window.print();
};

/**
 * Utility function to create a PDF from the invoice and trigger download
 * This uses jsPDF to create a proper PDF document with enhanced quality
 */
export const downloadInvoice = async (invoiceNumber: string): Promise<void> => {
  // Get the invoice element
  const invoiceElement = document.getElementById('invoice-preview');
  if (!invoiceElement) {
    console.error('Invoice element not found');
    toast.error('Could not generate PDF: Invoice element not found');
    return;
  }

  try {
    // Prepare the element for high-quality capture
    const originalStyles = {
      opacity: invoiceElement.style.opacity,
      transform: invoiceElement.style.transform,
      transition: invoiceElement.style.transition,
      boxShadow: invoiceElement.style.boxShadow,
      width: invoiceElement.style.width,
      margin: invoiceElement.style.margin,
    };
    
    // Enhance for PDF capture
    invoiceElement.style.opacity = '1';
    invoiceElement.style.transform = 'none';
    invoiceElement.style.transition = 'none';
    invoiceElement.style.boxShadow = 'none';
    invoiceElement.style.width = '100%';
    invoiceElement.style.margin = '0';
    
    // Set up html2canvas with optimal settings for A4 size
    const canvas = await html2canvas(invoiceElement, {
      scale: 2, // Balanced scale for quality and fitting
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      allowTaint: true,
      windowWidth: invoiceElement.scrollWidth,
      windowHeight: invoiceElement.scrollHeight,
      onclone: (clonedDoc) => {
        const clonedElement = clonedDoc.getElementById('invoice-preview');
        if (clonedElement) {
          // Add A4 size constraints and avoid page breaks
          const style = document.createElement('style');
          style.innerHTML = `
            @page {
              size: A4;
              margin: 0;
            }
            #invoice-preview {
              width: 210mm;
              max-height: 297mm;
              margin: 0 auto;
              box-sizing: border-box;
              overflow: hidden;
            }
            #invoice-preview * {
              max-width: 100%;
              box-sizing: border-box;
            }
            #invoice-preview table { page-break-inside: avoid; }
            #invoice-preview table td { word-break: break-word; }
          `;
          clonedDoc.head.appendChild(style);
          
          // Apply additional styling to ensure content fits properly
          clonedElement.style.pageBreakInside = 'avoid';
          clonedElement.style.printColorAdjust = 'exact';
          
          // Apply font smoothing through setAttribute to bypass TypeScript checking
          clonedElement.setAttribute('style', 
            clonedElement.getAttribute('style') + 
            '; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;'
          );
        }
      }
    });
    
    // Create PDF with A4 dimensions
    const imgData = canvas.toDataURL('image/png', 1.0);
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true,
      hotfixes: ['px_scaling'],
    });
    
    // Set document properties
    pdf.setProperties({
      title: `Invoice-${invoiceNumber}`,
      subject: 'Invoice Document',
      creator: 'AI Invoice Generator',
      author: 'AI Transactify',
    });
    
    // Calculate dimensions for proper A4 fitting
    const pdfWidth = 210; // A4 width in mm
    const pdfHeight = 297; // A4 height in mm
    
    // Set margins for better appearance
    const marginX = 10; // 10mm margin on left and right
    const marginY = 10; // 10mm margin on top and bottom
    
    // Calculate content dimensions to fit within margins
    const contentWidth = pdfWidth - (marginX * 2);
    const contentHeight = (canvas.height * contentWidth) / canvas.width;
    
    // Add image to PDF with proper A4 sizing
    pdf.addImage(
      imgData, 
      'PNG', 
      marginX, 
      marginY, 
      contentWidth, 
      Math.min(contentHeight, pdfHeight - (marginY * 2)) // Ensure it fits in one page
    );
    
    // Add footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by AI Transactify | Invoice #${invoiceNumber}`, 
      pdfWidth / 2, 
      pdfHeight - 5, 
      { align: 'center' }
    );
    
    // Save the PDF
    pdf.save(`Invoice-${invoiceNumber}-${new Date().toISOString().slice(0, 10)}.pdf`);
    
    // Restore original styles
    invoiceElement.style.opacity = originalStyles.opacity;
    invoiceElement.style.transform = originalStyles.transform;
    invoiceElement.style.transition = originalStyles.transition;
    invoiceElement.style.boxShadow = originalStyles.boxShadow;
    invoiceElement.style.width = originalStyles.width;
    invoiceElement.style.margin = originalStyles.margin;
    
    toast.success('PDF generated successfully');
  } catch (error) {
    console.error('Error generating PDF:', error);
    toast.error('Failed to generate PDF. Please try again.');
  }
};
