// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yihchfhesaqoteghneqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaGNoZmhlc2Fxb3RlZ2huZXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDc1NjYsImV4cCI6MjA1ODMyMzU2Nn0.mpCn0Juyq-mvB5ZMn8rd_vjn2lyQHXBi8wtk7kBAx5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);